# Generated by Django 6.0 on 2025-12-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_activation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ode_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
