# Generated by Django 6.0 on 2025-12-31 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_ode_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ode_created_at',
            new_name='code_created_at',
        ),
    ]
