# Generated by Django 6.0 on 2026-01-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localshop', '0002_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
